// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhtihvgymxsqeazykbca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodGlodmd5bXhzcWVhenlrYmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzE0MDYsImV4cCI6MjA1NzI0NzQwNn0.5OMQ7joPdVRtU0YdAYNudFENaDmfYjHXrbsvSoDxWbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);